// <auto-generated />
using System;
using AspNetCoreTodo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreTodo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190719232137_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("AspNetCoreTodo.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("DueAt");

                    b.Property<bool>("IsDone");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("808c1504-7899-45c0-9369-5dc12a662429"),
                            DueAt = new DateTimeOffset(new DateTime(2019, 7, 20, 20, 21, 36, 942, DateTimeKind.Unspecified).AddTicks(6868), new TimeSpan(0, -3, 0, 0, 0)),
                            IsDone = false,
                            Title = "Curso ASP.NET Core"
                        },
                        new
                        {
                            Id = new Guid("98ca59e2-4c74-4c57-b848-a8f77ee23a5c"),
                            DueAt = new DateTimeOffset(new DateTime(2019, 7, 20, 20, 21, 36, 946, DateTimeKind.Unspecified).AddTicks(1648), new TimeSpan(0, -3, 0, 0, 0)),
                            IsDone = false,
                            Title = "Curso React"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
